"""add index on incidents created_at

Revision ID: 1214ee72b39e
Revises: bb4ceecf8220
Create Date: 2026-02-04 18:09:08.862250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1214ee72b39e'
down_revision: Union[str, None] = 'bb4ceecf8220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
