"""add deleted_at to incidents

Revision ID: d13b2d87b6c7
Revises: 1214ee72b39e
Create Date: 2026-02-04 18:22:41.423471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13b2d87b6c7'
down_revision: Union[str, None] = '1214ee72b39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'deleted_at')
    # ### end Alembic commands ###
